### ISSUE TITLE
Crash on Termux

### ISSUE THREAD

**Issue by XenotriX** [XenotriX/ghclone#2]
The application crashes when searching.

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ghclone", line 10, in <module>
    sys.exit(ghclone.main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ghclone/ghclone.py", line 99, in main
    curses.wrapper(tui)
  File "/data/data/com.termux/files/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ghclone/ghclone.py", line 41, in tui
    search(search_input.value(), repolist)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ghclone/ghclone.py", line 91, in search
    repos.set_repos(repolist)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ghclone/ghclone.py", line 112, in set_repos
    self.update()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ghclone/ghclone.py", line 121, in update
    self.win.addstr(index, 0, repo)
_curses.error: addwstr() returned ERR
```

**Comment by XenotriX** [comment]
This has been fixed in f7bb240
